[build-system]
requires = ["setuptools>=61.0", "build", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sqliteai-vector"
dynamic = ["version", "classifiers"]
description = "Python prebuilt binaries for SQLite Vector extension for all supported platforms and architectures."
authors = [
    { name = "SQLite AI Team" }
]
readme = "README.md"
license = "LicenseRef-Elastic-2.0-Modified-For-Open-Source-Use"
license-files = ["LICENSE.md"]
requires-python = ">=3"

[project.urls]
Homepage = "https://sqlite.ai"
Documentation = "https://github.com/sqliteai/sqlite-vector/blob/main/API.md"
Repository = "https://github.com/sqliteai/sqlite-vector"
Issues = "https://github.com/sqliteai/sqlite-vector/issues"

[tool.setuptools]
packages = {find = {where = ["src"]}}
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "sqlite_vector._version.__version__"}

[tool.bdist_wheel]
# Force platform-specific wheels
universal = false
